# File generated by @bazel_ipfs//fetch_versions:main

GO_IPFS_DIST_DICT = {
    "darwin": {"amd64": {
        "v0.4.18": {
            "sri": "sha512-YM+jkg/7nojQZgHnJzdsU2/I0x85KlSkxsGIqHRJs2J+Elhwhl8PXu2tanBpkUL96HYRZqeSGqjliONBt7ZTyQ==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_darwin-amd64.tar.gz",
        },
        "v0.4.19": {
            "sri": "sha512-RFNJnoP5qYDG3UI9Va5ok9SKFsO+uroL2KxpYeS3XX4grHqhJaPYi6rDIzs1NqJGFEs5/zqR7IrWphSCKSNp9Q==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_darwin-amd64.tar.gz",
        },
        "v0.4.20": {
            "sri": "sha512-QAtJJFKvQNOCqSaY3b/AdYYzNnKNZ3Sxno8cavyDMXHgKIdV1lIxhrQ5n916974duZBXsYmHHbTyZd12CvWIFA==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.20/go-ipfs_v0.4.20_darwin-amd64.tar.gz",
        },
        "v0.4.21": {
            "sri": "sha512-y7hVYBgqavQYcCmyRBSiF9cGxN1jaqBjQGFHnRA8qeyflLRHh9Ex6Wl9E0fGAm3ULnCpGF4JF5ILvoHwEBVAUQ==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_darwin-amd64.tar.gz",
        },
        "v0.4.22": {
            "sri": "sha512-0OebD/9VXCPDYo4aGCwxLNGONqgccfl2dd8IOt3j93Mw4/52N18fshLYHOlu6koW69n0yHxstOtS0CEPQv+0tA==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_darwin-amd64.tar.gz",
        },
        "v0.4.22-rc1": {
            "sri": "sha512-i3yGgWi729FpJNahfzieuIo9PpDouAaDjomgIIa28hqX2lFGPjo2vKKG3fmUUQk8m+64C3RbIAMaYbMhWQ1kIg==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.22-rc1/go-ipfs_v0.4.22-rc1_darwin-amd64.tar.gz",
        },
    }},
    "linux": {"amd64": {
        "v0.4.18": {
            "sri": "sha512-71tEoKrtYEiQyDMiygIigGEgQIW4eyDdFz7f5rZjH8elRyTS4AICSIyGiGmSoNQJ9D4J8CLN+LETj4QZz3YUsA==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-amd64.tar.gz",
        },
        "v0.4.19": {
            "sri": "sha512-ZtkwvvAZbHDyXLIHwA2m429sLBf/DnhfRdNg5xBQLCM67uqqXuC/yYSRnUIiXHTGR05eXOXIzWmTWAkD+o7AxA==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_linux-amd64.tar.gz",
        },
        "v0.4.20": {
            "sri": "sha512-qKLsnASnrsV2+Lhpl9UxC3fsoreN+cJprJ70eNeGJ3VQ8J5BDjku3jM+tlLo7RNrtYoi8rMZjJSmFknHpVJbaA==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.20/go-ipfs_v0.4.20_linux-amd64.tar.gz",
        },
        "v0.4.21": {
            "sri": "sha512-80SWnK1MKk+BaSxefhHa/EIGlGU/o30eOJtcRY7ojqNOoi7863RzUbtXkkfxxJTkf2Z+eheOgZe6TK1DpuUvhw==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_linux-amd64.tar.gz",
        },
        "v0.4.22": {
            "sri": "sha512-Sbmf7HQdZ/e62Ptvu9mEln8G38PehG0Q3KNLFm9iGhgtEvE89cz05PM3R7Z87eb0IFtM2bV85SRBKNE4XsgshQ==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_linux-amd64.tar.gz",
        },
        "v0.4.22-rc1": {
            "sri": "sha512-nJ7L/MbL5mnRyuPPLTpnI8UmuJMBQp5+bGBDBpfPe4BbGOm/fbgd2ybBC9oAGIBom9eLTO/6FKuZNVrreJMGZg==",
            "url": "https://dist.ipfs.io/go-ipfs/v0.4.22-rc1/go-ipfs_v0.4.22-rc1_linux-amd64.tar.gz",
        },
    }},
}
