workspace(name = "bazel_ipfs_usage_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_pkg",
    sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
)

local_repository(
    name = "bazel_ipfs",
    path = "..",
)

load("@bazel_ipfs//:index.bzl", "ipfs_archive", "ipfs_tools_repository")

ipfs_tools_repository(name = "bazel_ipfs_tools")

ipfs_archive(
    name = "hello_ipfs",
    extension = "tar.gz",
    ref_file = "//:archive.ref",
)

# same as above
ipfs_archive(
    name = "hello_ipfs_str_ref",
    extension = "tar.gz",
    ref = "QmcLRC75TFap4UrMd1QUuTatEMazxhE8yV7PCYJZg6guMW",
)
